### ISSUE TITLE
(Solved) Undefined property: stdClass::$payBoleto

### ISSUE THREAD

**Issue by Jackcar** [wirecardBrasil/moip-sdk-php#307]
Ola,

Estava tentando realizar um multipagamento utilizando o SDK e tive o seguinte retorno:
`"message":"Notice: Undefined property: stdClass::$payBoleto in \/vendor\/moip\/moip-sdk-php\/src\/Resource\/Payment.php on line 278"`.

Acabei corrigindo e o erro estava ao tentar pegar os valores 'redirectHref' e 'printHref' do server response.

Fiz a seguinte mudança na linha 278:
`$this->getIfSet('_links')->payBoleto->redirectHref;`
Para:
`$this->getIfSet('_links')->checkout->payBoleto->redirectHref;`

Melhor ainda se verificar se é um multipagamento e incluir as alterações. 

Abraços.

**Comment by SOSTheBlack** [comment]
@Jackcar obrigado por postar a solução
